---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  labels:
    app: dragonfly
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dragonfly
  template:
    metadata:
      labels:
        app: dragonfly
    spec:
      containers:
      - name: dragonfly
        image: dragonapp:latest
        imagePullPolicy : IfNotPresent
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: dragon-svc
  labels:
    app: dragonfly
spec:
  selector:
    app: dragonfly
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081
~                      
